//Action Types
export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE';

//action type for confirmed order
export const CONFIRMED_ORDERS_REQUEST = 'CONFIRMED_ORDERS_REQUEST';
export const CONFIRMED_ORDERS_SUCCESS = 'CONFIRMED_ORDERS_SUCCESS';
export const CONFIRMED_ORDERS_FAILURE = 'CONFIRMED_ORDERS_FAILURE';

//action type for placed order 
export const PLACED_ORDERS_REQUEST = 'PLACED_ORDERS_REQUEST';
export const PLACED_ORDERS_SUCCESS = 'PLACED_ORDERS_SUCCESS';
export const PLACED_ORDERS_FAILURE = 'PLACED_ORDERS_FAILURE';

// Action types for delivered order 
export const DELEVERED_ORDERS_REQUEST = 'DELEVERED_ORDERS_REQUEST';
export const DELEVERED_ORDERS_SUCCESS = 'DELEVERED_ORDERS_SUCCESS';
export const DELEVERED_ORDERS_FAILURE = 'DELEVERED_ORDERS_FAILURE';

// Action type for canceled order
export const CONCELED_ORDERS_REQUEST = 'CONCELED_ORDERS_REQUEST';
export const CONCELED_ORDERS_SUCCESS = 'CONCELED_ORDERS_SUCCESS';
export const CONCELED_ORDERS_FAILURE = 'CONCELED_ORDERS_FAILURE';
// Action type for delete order
export const DELETE_ORDERS_REQUEST = 'DELETE_ORDERS_REQUEST';
export const DELETE_ORDERS_SUCCESS = 'DELETE_ORDERS_SUCCESS';
export const DELETE_ORDERS_FAILURE = 'DELETE_ORDERS_FAILURE';
// Action type for ship order
export const SHIP_ORDERS_REQUEST = 'SHIP_ORDERS_REQUEST';
export const SHIP_ORDERS_SUCCESS = 'SHIP_ORDERS_SUCCESS';
export const SHIP_ORDERS_FAILURE = 'SHIP_ORDERS_FAILURE';
